# Generated by Django 5.0.14 on 2026-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_id_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card (National ID)'), ('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', 'Drivers License')], default='national_id', max_length=30),
        ),
    ]
